extends Node

signal player_won
signal player_lost
signal first_game_started
signal game_starting
signal finger_locked
signal finger_unlocked

signal speech_finished_sentence
signal speech_finished_text

signal intro_finished
signal background_sounds_to_menu
signal background_sounds_to_level
signal background_sounds_to_excited
